version: "2"
services:
  app:
    build: ./app
    container_name: "Flask_App"
    links:
      - db
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - user
      - pass
      - host
      - database
      - port